title: Backend Engineering Onboarding | The Iron Yard - Washington DC
project_name: Backend Engineering
description: >
  The Iron Yard - The Iron Yard - Washington DC
repository_url: https://github.com/TIY-DC-ROR-2016-FEB/onboarding
repository_shorthand: TIY-DC-ROR-2016-FEB/onboarding
baseurl: /onboarding
author_name: Russell Osborne
author_email: russell@theironyard.com
author_url: https://github.com/rposborne
markdown: kramdown
